services:
  postgres:
    container_name: phoenix-postgres
    build:
      context: ./services/postgres/
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -h localhost -U postgres -d phoenix"
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - ./services/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    labels:
      - "project=phoenix"

  api:
    container_name: phoenix-api
    build:
      context: ./services/api/
    ports:
      - 8000:8000
    volumes:
      - ./services/api/app:/code/app:rw
    env_file:
      - services/api/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "project=phoenix"
    depends_on:
      postgres:
        condition: service_healthy

  client:
    container_name: phoenix-client
    build:
      context: ./services/client/
      target: production
    ports:
      - 3000:3000
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - services/client/.env
    labels:
      - "project=phoenix"

volumes:
  db-data:
    labels:
      - "project=phoenix"
