services:
  chroma:
    container_name: phoenix-chroma
    build:
      context: ./services/chroma/
    ports:
      - 8001:8001
    volumes:
      - ./services/chroma/data:/data
    labels:
      - "project=phoenix"

  api:
    container_name: phoenix-api
    depends_on:
      - chroma
    build:
      context: ./services/api/
    ports:
      - 8000:8000
    volumes:
      - ./services/api/app:/code/app:rw
    env_file:
      - services/api/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chroma:8001"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "project=phoenix"

  client:
    container_name: phoenix-client
    build:
      context: ./services/client/
      target: production
    ports:
      - 3000:3000
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - services/client/.env
    labels:
      - "project=phoenix"

volumes:
  chroma_data:
    labels:
      - "project=phoenix"
